networks:
  transcendence:
    name : ${NETWORK_NAME}
    driver: bridge

volumes:
  database_volume:
    name: ${DB_VOLUME_NAME}
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: ${HOME}/data/${DB_VOLUME_NAME}


services:

#           DATABASE RDBMS = PostgreSQL
  postgresql-rdbms:
    container_name: postgresql-rdbms
    image: postgres:17-bookworm        # No Dockerfile needed here!
    restart: unless-stopped
    expose:
      - "${POSTGRES_PORT}"
    environment: # Postgres Docker image need them through environment - to specifically overwrite the defaults of the first 3 here
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_admin_password.txt
      POSTGRES_AUTH_USER_PASSWORD_FILE: /run/secrets/db_auth_password.txt
      POSTGRES_WEBSITE_USER_PASSWORD_FILE: /run/secrets/db_website_password.txt
      POSTGRES_GAME_USER_PASSWORD_FILE: /run/secrets/db_game_password.txt
      POSTGRES_BOT_USER_PASSWORD_FILE: /run/secrets/db_bot_password.txt
      POSTGRES_CHAT_USER_PASSWORD_FILE: /run/secrets/db_chat_password.txt
    env_file:
      - .env
    volumes:
      - database_volume:/var/lib/postgresql/data                                                              # volume
      - ./secrets/database_passwords:/run/secrets:ro      # secrets
      - ./packages/database/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro                             # to run schema creation script
      - ./packages/database/scripts:/scripts:ro
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  
#           Drizzle = ORM - a library
#           DATA BROWSER = Drizzle Studio, Dev-only Database Tool, a CLI tool inside Node environment (thats why node image)
  drizzle-studio:
    container_name: drizzle-studio
    image: drizzle-studio:aisyah
    build: 
      context: .
      dockerfile: ./packages/database/Dockerfile              # gets the built (main application), built once only -> efficient + saves CPU and disk space. 
    pull_policy: build                                        # This forces local builds, ignoring Docker Hub
    restart: unless-stopped
    ports:
      - "${DRIZZLE_STUDIO_PORT}:${DRIZZLE_STUDIO_PORT}"
    env_file:
      - .env                                  
    volumes:
      - ./secrets/database_passwords/db_admin_password.txt:/run/secrets/db_admin_password.txt:ro
    command: npx drizzle-kit studio --port ${DRIZZLE_STUDIO_PORT}
    # command: docker exec -it drizzle-orm /bin/sh
    networks:
      - transcendence
    depends_on:
      postgresql-rdbms:
        condition: service_healthy

#           AUTHENTICATION
  auth:
    container_name: auth
    build: ./backend-services/authentication/.
    image: auth:jeremy
    pull_policy: build
    restart: unless-stopped
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      DB_HOST: postgresql-rdbms                           # DB_HOST is a standard industry convention
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}                           # ${POSTGRES_USER_NAME_AUTH}
      DB_PASSWORD: /run/secrets/db_admin_password.txt     # /run/secrets/db_auth_password.txt
    env_file:
      - .env                                              # Loads global configs
      - backend-services/authentication/.env              # Loads service-specific configs
    volumes:
      - ./secrets/database_passwords/db_auth_password.txt:/run/secrets/db_auth_password.txt:ro # => will be inside auth's .env
      - ./secrets/database_passwords/db_admin_password.txt:/run/secrets/db_admin_password.txt:ro
    networks:
      - transcendence
    depends_on:
      postgresql-rdbms:
        condition: service_healthy


#         GAME-FRONTEND
#         GAME-BACKEND
#         GAME-BOT
#         WEBSITE + NGINX (only backend has to be seperate micoservices with seperate 1 responsibiliyty -> PDF)
#         CHAT
#         OTHERS (still learning now)


# NOTES:
# env_file placement
  # can have env_file at the bottom => Docker Compose processes the file in stages, rather than reading it line-by-line from top to bottom.
  # environment overrides .env if vars exits in both, both can co-exist in docker-compose
  # image syntax => image: version-tag
# Drizzle Studio, need HTTPS?
  # The requirement "HTTPS everywhere" applies to your production application (You must encrypt all traffic between your users and your API Gateway)
  # No need HTTPS for Drizzle Studio, coz its a local development-only tool, should never be exposed to the public internet. 
  # Accessing it at http://localhost:(port) is standard and perfectly acceptable for your development environment, keep it out of production entirely to avoid massive security holes
