networks:
  big2:
    name : big2
    driver: bridge

volumes:
  postgresql_data:
    name: postgresql_data
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: ${PWD}/data/postgresql_data


services:

#           DATABASE RDBMS = PostgreSQL
  postgresql-rdbms:
    container_name: postgresql-rdbms
    image: postgres:17-bookworm                 # No Dockerfile needed here!
    restart: unless-stopped
    expose:
      - "${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ../secrets/database_password.txt:/run/secrets/database_password:ro
    networks:
      - big2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  
#           Drizzle = ORM - a library
#           DATA BROWSER = Drizzle Studio, Dev-only Database Tool, a CLI tool inside Node environment (thats why node image)
  drizzle-orm:
    container_name: drizzle-orm
    build: ./packages/database/.              # gets the built (main application), built once only -> efficient + saves CPU and disk space. 
    pull_policy: build                        # This forces local builds, ignoring Docker Hub
    restart: unless-stopped
    ports:
      - "${DRIZZLE_STUDIO_PORT}:${DRIZZLE_STUDIO_PORT}"
    env_file:
      - .env
    volumes:
      - ../secrets/database_password.txt:/run/secrets/database_password:ro
    networks:
      - big2
    depends_on:
      postgresql-rdbms:
        condition: service_healthy

#           AUTHENTICATION
  auth:
    container_name: auth
    build: ./backend-services/authentication/.
    image: auth:jeremy
    pull_policy: build
    restart: unless-stopped
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      PORT: ${AUTH_PORT}
    env_file:
      - .env
    volumes:
      - ../secrets/database_password.txt:/run/secrets/database_password:ro
    networks:
      - big2
    depends_on:
      postgresql-rdbms:
        condition: service_healthy


#         GAME-FRONTEND
#         GAME-BACKEND
#         GAME-BOT
#         WEBSITE + NGINX (only backend has to be seperate micoservices with seperate 1 responsibiliyty -> PDF)
#         CHAT
#         OTHERS (still learning now)


# NOTES:
# env_file placement
  # can have env_file at the bottom => Docker Compose processes the file in stages, rather than reading it line-by-line from top to bottom.
  # environment overrides .env if vars exits in both, both can co-exist in docker-compose
  # image syntax => image: version-tag
# Drizzle Studio, need HTTPS?
  # The requirement "HTTPS everywhere" applies to your production application (You must encrypt all traffic between your users and your API Gateway)
  # No need HTTPS for Drizzle Studio, coz its a local development-only tool, should never be exposed to the public internet. 
  # Accessing it at http://localhost:(port) is standard and perfectly acceptable for your development environment, keep it out of production entirely to avoid massive security holes
