# NOTES:
# ports: 
  # - ${ENV_VARIABLE:-DEFAULT}
# Docker Compose processes the file in stages, rather than reading it line-by-line from top to bottom.
# therefore, can have env_file at the bottom
# environment overrides .env if vars exits in both, both can co-exist in docker-compose


networks:
  transcendence:
    name : transcendence
    driver: bridge

volumes:
  postgresql_data:
    name: postgresql_data
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: /home/aimokhta/data/postgresql_data

services:
#           DATABASE = PostgreSQL
  database:
    container_name: database
    image: postgres:17-bookworm     # No Dockerfile needed here!
    restart: unless-stopped
    expose:
      - "${DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRISMA_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${PRISMA_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ../secrets/database_password.txt:/run/secrets/database_password:ro
    networks:
      - transcendence
  
#           BACKEND = Prisma + Socket.io + Node.js + Express.js
  backend:
    container_name: backend
    build: ./services/backend/. # gets the built (main application), built once only -> efficient + saves CPU and disk space. 
    image: backend:aisyah       # identical image as prisma_studio, with different command -> "npm run start"
    pull_policy: build          # This forces local builds, ignoring Docker Hub
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      PORT: ${BACKEND_PORT}
      # DATABASE_URL: -> defined in entrypoint.sh
    env_file:
      - .env
    volumes:
      - ../secrets/database_password.txt:/run/secrets/database_password:ro
    networks:
      - transcendence
    depends_on:
      database:
        condition: service_healthy


#         VISUAL DATA BROWSER = Prisma Studio
#         command in docker compose => overwrites Dockerfile's CMD
#         entrypoint in docker compose => overwrites Dockerfile's ENTRYPOINT
  prisma_studio:
    container_name: prisma_studio
    image: backend:aisyah   # just referencing the backend's image (reuse only), with different command -> docker-compose's command:
    pull_policy: build      # This forces local builds, ignoring Docker Hub
    entrypoint: "/usr/local/bin/prisma_studio-entrypoint.sh"
    command: npx prisma studio --port ${PRISMA_STUDIO_PORT} --hostname 0.0.0.0   # hardcode 0.0.0.0 (required for Docker containers)
    ports:
      - "${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}"
    env_file:
      - .env
    volumes:
      - ../secrets/database_password.txt:/run/secrets/database_password:ro
    networks:
      - transcendence
    depends_on:
      database:
        condition: service_healthy
      # backend:
      #   condition: service_completed_successfully => cannot => If backend finishes (or crashes), your prisma_studio will stop. Prisma Studio is a utility, not a service that depends on the backend finishing.



