error_log /var/log/nginx/error.log warn;
error_log /dev/stderr warn;

worker_processes 1;

events {
	worker_connections 1024;
}

http {
	access_log off;

	server {
		listen 80;

		# location / {
		# 	proxy_pass http://website:5173;
			
		# 	proxy_http_version 1.1;
		# 	proxy_set_header Upgrade $http_upgrade;
	    #     proxy_set_header Connection "upgrade";
		# }

		location /api/auth/ {
			proxy_pass http://authentication:3000/;
			
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

		# location /socket/party/ {
		# 	proxy_pass http://party-manager:3000/socket.io/;

		# 	proxy_http_version 1.1;
		# 	proxy_set_header Upgrade $http_upgrade;
		# 	proxy_set_header Connection "upgrade";
		# }

		# location /socket/game/ {
		# 	proxy_pass http://game:3000/;
			
		# 	proxy_http_version 1.1;
		# 	proxy_set_header Upgrade $http_upgrade;
		# 	proxy_set_header Connection "upgrade";
		# }
	}
}
